/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint8_t _estack; /* Symbol defined in the linker script */
  extern uint32_t _Min_Stack_Size; /* Symbol defined in the linker script */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  const uint8_t *max_heap = (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* Protect heap from growing into the reserved MSP stack */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}

#if defined(__PICOLIBC__)
  // Picolibc expects syscalls without the leading underscore.
  // This creates a strong alias so that
  // calls to `sbrk()` are resolved to our `_sbrk()` implementation.
  __strong_reference(_sbrk, sbrk);
#endif

#if !defined(__PICOLIBC__)
#include <sys/reent.h>
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"

/* Newlib-nano malloc thread-safety lock — INTERRUPT-SAFE version.
 *
 * Problem context:
 *   - lwipopts.h configures MEM_LIBC_MALLOC=1 and MEMP_MEM_MALLOC=1, so every
 *     lwIP pbuf/memp allocation is served by newlib-nano malloc/free.
 *   - newlib-nano's default __malloc_lock/__malloc_unlock (libc_a-mlock.o) are
 *     empty stubs, so libc malloc is NOT thread-safe. Under concurrent
 *     malloc/free the heap free-list gets corrupted -> HardFault inside
 *     _malloc_r (e.g. dereferencing 0xFFFFFFFC, BFAR in the fault frame).
 *
 *   - The FIRST fix here used a FreeRTOS recursive mutex. It removed the heap
 *     corruption, but xSemaphoreTakeRecursive() may NOT be called from an ISR.
 *     lwIP can allocate through newlib from an interrupt callback (e.g. an ETH
 *     RX/TX callback running under the ETH IRQ); there xSemaphoreTakeRecursive
 *     trips a FreeRTOS assert and the system wedges -> IWDG starves -> reset.
 *     This exactly matches "frequent UDP traffic resets the board".
 *
 *   Fix: protect the newlib heap with a critical section instead of a mutex.
 *   A critical section is valid in BOTH task and ISR context:
 *     - task context: taskENTER_CRITICAL      / taskEXIT_CRITICAL
 *     - ISR  context: taskENTER_CRITICAL_FROM_ISR / taskEXIT_CRITICAL_FROM_ISR
 *   Critical sections nest (FreeRTOS keeps a nesting counter), so re-entrant
 *   malloc is also safe. While the CPU is locked, no task/ISR preemption can
 *   interleave on the heap, eliminating both the corruption AND the ISR
 *   assert/hang.
 *
 *   Trade-off: malloc briefly disables interrupts. lwIP pbuf allocs are short
 *   (microseconds) and the ETH DMA runs independently of the CPU, so the
 *   real-time impact is small. Do not call malloc from inside a long critical
 *   section elsewhere, to avoid widening this lock window.
 *
 *   Note: ulMallocLockSavedState is a single global. This is correct as long as
 *   malloc is not entered re-entrantly from *different* nested ISR priorities
 *   (lwIP does not do this). The task-context path does not touch this global.
 */
static UBaseType_t ulMallocLockSavedState = 0;

void __malloc_lock(struct _reent *reent)
{
    (void)reent;

    if (xPortIsInsideInterrupt())
    {
        ulMallocLockSavedState = taskENTER_CRITICAL_FROM_ISR();
    }
    else
    {
        taskENTER_CRITICAL();
    }
}

void __malloc_unlock(struct _reent *reent)
{
    (void)reent;

    if (xPortIsInsideInterrupt())
    {
        taskEXIT_CRITICAL_FROM_ISR(ulMallocLockSavedState);
    }
    else
    {
        taskEXIT_CRITICAL();
    }
}
#endif /* !__PICOLIBC__ */
