/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint8_t _estack; /* Symbol defined in the linker script */
  extern uint32_t _Min_Stack_Size; /* Symbol defined in the linker script */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  const uint8_t *max_heap = (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* Protect heap from growing into the reserved MSP stack */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}

#if defined(__PICOLIBC__)
  // Picolibc expects syscalls without the leading underscore.
  // This creates a strong alias so that
  // calls to `sbrk()` are resolved to our `_sbrk()` implementation.
  __strong_reference(_sbrk, sbrk);
#endif


#if !defined(__PICOLIBC__)
#include <sys/reent.h>
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"

/* Newlib-nano malloc thread-safety lock.
 *
 * Problem context:
 *   - lwipopts.h configures MEM_LIBC_MALLOC=1 and MEMP_MEM_MALLOC=1,
 *     so every lwIP pbuf/memp allocation is served by newlib-nano malloc/free.
 *   - lwIP pbuf alloc/free can occur concurrently from multiple tasks:
 *     Udp_discover_task, Tcp_client_task, the lwIP tcpip thread, etc.
 *   - newlib-nano's default __malloc_lock/__malloc_unlock (from libc_a-mlock.o)
 *     are empty stubs. Consequently libc malloc is NOT thread-safe.
 *   - Under concurrent malloc/free the heap free-list gets corrupted; the first
 *     symptom is typically a HardFault inside _malloc_r when it dereferences a
 *     corrupted next-pointer such as 0xFFFFFFFC (BFAR in the fault frame).
 *
 * Fix:
 *   Override the weak newlib-nano stubs with a FreeRTOS recursive mutex.
 *   The mutex is lazily initialized (with a critical-section double-check) so it
 *   is ready the first time malloc is called after the scheduler starts.
 */
static SemaphoreHandle_t xMallocMutex = NULL;
static StaticSemaphore_t xMallocMutexBuffer;

void __malloc_lock(struct _reent *reent)
{
    (void)reent;

    /* Before the scheduler is running there is only one execution context,
     * so no cross-task locking is needed. */
    if (xTaskGetSchedulerState() == taskSCHEDULER_NOT_STARTED)
    {
        return;
    }

    /* Lazy initialization, protected against races on the first malloc call. */
    if (xMallocMutex == NULL)
    {
        taskENTER_CRITICAL();
        if (xMallocMutex == NULL)
        {
            xMallocMutex = xSemaphoreCreateRecursiveMutexStatic(&xMallocMutexBuffer);
        }
        taskEXIT_CRITICAL();
    }

    if (xMallocMutex != NULL)
    {
        (void)xSemaphoreTakeRecursive(xMallocMutex, portMAX_DELAY);
    }
}

void __malloc_unlock(struct _reent *reent)
{
    (void)reent;

    if (xMallocMutex != NULL)
    {
        (void)xSemaphoreGiveRecursive(xMallocMutex);
    }
}
#endif /* !__PICOLIBC__ */

